name: MultiTTA
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.8
  - aom=3.5.0
  - attr=2.5.1
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - cfitsio=3.470
  - charls=2.2.0
  - click=8.1.8
  - cloudpickle=3.1.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=0.11.2
  - dask-core=2025.4.1
  - dav1d=1.2.1
  - dbus=1.13.6
  - expat=2.7.1
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freeglut=3.2.2
  - freetype=2.13.3
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.41
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=70.1
  - imagecodecs=2023.1.23
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - jack=1.9.22
  - jasper=2.0.33
  - joblib=1.4.2
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20250127.0
  - libaec=1.1.3
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.12.1
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=3.0.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libglu=9.0.0
  - libgomp=14.2.0
  - libgpg-error=1.55
  - libiconv=1.18
  - libidn2=2.3.8
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopencv=4.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=253
  - libtasn1=4.20.0
  - libtiff=4.5.1
  - libtool=2.5.4
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpg123=1.32.9
  - mysql=8.0.32
  - mysql-client=8.0.32
  - mysql-common=8.0.32
  - mysql-devel=8.0.32
  - mysql-libs=8.0.32
  - mysql-server=8.0.32
  - ncurses=6.4
  - nettle=3.9.1
  - nspr=4.36
  - nss=3.100
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.1.8
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - partd=1.4.2
  - pcre2=10.42
  - pillow=10.3.0
  - pip=25.0
  - pixman=0.44.2
  - ply=3.11
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - py-opencv=4.7.0
  - pyparsing=3.0.9
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqt6-sip=13.9.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - qt-main=5.15.8
  - readline=8.2
  - scikit-image=0.19.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - setuptools=75.8.0
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - svt-av1=1.4.1
  - tbb=2021.8.0
  - threadpoolctl=3.6.0
  - tifffile=2023.8.12
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - tzdata=2025a
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - filelock==3.13.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - sympy==1.13.3
      - torch==2.7.0+cu118
      - torchaudio==2.7.0+cu118
      - torchvision==0.22.0+cu118
      - triton==3.3.0
      - typing-extensions==4.12.2
prefix: /home/yezhong/miniconda3/envs/MultiTTA
